%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(errors_types).

-include("errors_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('EDAMUserException') ->
  {struct, [{1, i32},
          {2, string}]}
;

struct_info('EDAMSystemException') ->
  {struct, [{1, i32},
          {2, string},
          {3, i32}]}
;

struct_info('EDAMNotFoundException') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('EDAMUserException') ->
  {struct, [{1, required, i32, 'errorCode', undefined},
          {2, optional, string, 'parameter', undefined}]}
;

struct_info_ext('EDAMSystemException') ->
  {struct, [{1, required, i32, 'errorCode', undefined},
          {2, optional, string, 'message', undefined},
          {3, optional, i32, 'rateLimitDuration', undefined}]}
;

struct_info_ext('EDAMNotFoundException') ->
  {struct, [{1, optional, string, 'identifier', undefined},
          {2, optional, string, 'key', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

