%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(second_service_thrift).
-behaviour(thrift_service).


-include("second_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% blahBlah(This)
function_info('blahBlah', params_type) ->
  {struct, []}
;
function_info('blahBlah', reply_type) ->
  {struct, []};
function_info('blahBlah', exceptions) ->
  {struct, []}
;
% secondtestString(This, Thing)
function_info('secondtestString', params_type) ->
  {struct, [{1, string}]}
;
function_info('secondtestString', reply_type) ->
  string;
function_info('secondtestString', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

