%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(thrift1151_types).

-include("thrift1151_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('StructA') ->
  {struct, [{1, i16}]}
;

struct_info('StructB') ->
  {struct, [{1, i32}]}
;

struct_info('StructC') ->
  {struct, [{1, {struct, {'thrift1151_types', 'StructA'}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('StructA') ->
  {struct, [{1, undefined, i16, 'x', undefined}]}
;

struct_info_ext('StructB') ->
  {struct, [{1, undefined, i32, 'x', undefined}]}
;

struct_info_ext('StructC') ->
  {struct, [{1, undefined, {struct, {'thrift1151_types', 'StructA'}}, 'x', #'StructA'{}}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

