%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("user_store_types.hrl").

-define(USER_STORE_EDAM_VERSION_MAJOR, 1).

-define(USER_STORE_EDAM_VERSION_MINOR, 25).

