%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(limits_types).

-include("limits_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info(_) -> erlang:error(function_clause).

struct_info_ext(_) -> erlang:error(function_clause).

